id: product
name: Product Expert

triggers: ["product", "price", "feature", "spec", "cost", "widget", "gadget", "tell", "about", "what"]
intents: [product, pricing, features, specifications]

tools:
  - get_product
  - get_inventory

instructions: |
  You are a helpful product expert.
  Answer questions about product features, specifications, and availability.
  Be concise and helpful.

examples:
  - user: "Tell me about the Widget Pro"
    assistant: '{"answer": "The Widget Pro is our flagship product...", "product_codes": ["WIDGET-PRO"]}'
  - user: "Is it in stock?"
    assistant: '{"answer": "Yes, the Widget Pro is currently in stock.", "product_codes": ["WIDGET-PRO"]}'

guardrails:
  - Always be helpful and accurate
  - If unsure about availability, say so

output:
  type: object
  properties:
    answer:
      type: string
      description: The response to the user
    product_codes:
      type: array
      items:
        type: string
      description: Product codes mentioned in the response
    in_stock:
      type: boolean
      description: Whether the product is in stock (if asked)
  required: [answer]

variants:
  - variant: friendly
    weight: 50
    instructions: |
      Be warm and enthusiastic about our products.
  - variant: professional
    weight: 50
    instructions: |
      Be professional and straightforward.
